// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BookSmart.Models
{
    public partial class BookSmartDBContext : DbContext
    {
        IConfiguration _configuration;
        public BookSmartDBContext(IConfiguration configuration)
        {
            _configuration = configuration; 
        }

        public BookSmartDBContext(DbContextOptions<BookSmartDBContext> options, IConfiguration configuration)
            : base(options)
        {
            _configuration = configuration;
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookClass> BookClasses { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassTeacher> ClassTeachers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectTeacher> SubjectTeachers { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var username = _configuration.GetValue<string>("DBLogin");
                var password = _configuration.GetValue<string>("Password");
                optionsBuilder.UseSqlServer($"Server=tcp:booksmartdbserver.database.windows.net,1433;Initial Catalog=BookSmartDB;Persist Security Info=False;User ID={username};Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
            }
        
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>(entity =>
            {
                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.Books)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Book__Subject_id__00200768");
            });

            modelBuilder.Entity<BookClass>(entity =>
            {
                entity.HasKey(e => e.BcId)
                    .HasName("PK__tmp_ms_x__29E996164F04194C");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.BookClasses)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Book-Clas__Book___30C33EC3");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.BookClasses)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Book-Clas__Class__2FCF1A8A");
            });

            modelBuilder.Entity<Class>(entity =>
            {
                entity.Property(e => e.ClassId).ValueGeneratedNever();
            });

            modelBuilder.Entity<ClassTeacher>(entity =>
            {
                entity.HasKey(e => e.CtId)
                    .HasName("PK__tmp_ms_x__DC4E3A73A1DCC1BF");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.ClassTeachers)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Class-Tea__Class__29221CFB");

                entity.HasOne(d => d.InitialsNavigation)
                    .WithMany(p => p.ClassTeachers)
                    .HasForeignKey(d => d.Initials)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Class-Tea__Initi__282DF8C2");
            });

            modelBuilder.Entity<SubjectTeacher>(entity =>
            {
                entity.HasKey(e => e.StId)
                    .HasName("PK__tmp_ms_x__EBD417B737E4F1A8");

                entity.HasOne(d => d.InitialsNavigation)
                    .WithMany(p => p.SubjectTeachers)
                    .HasForeignKey(d => d.Initials)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Subject-T__Initi__2CF2ADDF");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.SubjectTeachers)
                    .HasForeignKey(d => d.SubjectId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Subject-T__Subje__2BFE89A6");
            });

            modelBuilder.Entity<Teacher>(entity =>
            {
                entity.HasKey(e => e.Initials)
                    .HasName("PK__Teacher__F6EBAFF723CDF5FE");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}