// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BookSmart.Models
{
    public partial class BookSmartDBContext : DbContext
    {
        private readonly IConfiguration _configuration;
        public BookSmartDBContext(IConfiguration configuration)
        {
            _configuration = configuration;

        }

        public BookSmartDBContext(DbContextOptions<BookSmartDBContext> options, IConfiguration configuration)
            : base(options)
        {
            _configuration = configuration;
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookClass> BookClasses { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassTeacher> ClassTeachers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
               var username = _configuration.GetValue<string>("DBLogin");
               var password = _configuration.GetValue<string>("Password");
                optionsBuilder.UseSqlServer($"Server=tcp:booksmartdbserver.database.windows.net,1433;Initial Catalog=BookSmartDB;Persist Security Info=False;User ID={username};Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>(entity =>
            {
                entity.Property(e => e.BookId).ValueGeneratedNever();
            });

            modelBuilder.Entity<BookClass>(entity =>
            {
                entity.HasKey(e => e.BcId)
                    .HasName("PK__Book-Cla__29E9961601C151D0");

                entity.Property(e => e.BcId).ValueGeneratedNever();
            });

            modelBuilder.Entity<Class>(entity =>
            {
                entity.HasKey(e => e.Name)
                    .HasName("PK__Class__737584F72FA11E43");
            });

            modelBuilder.Entity<ClassTeacher>(entity =>
            {
                entity.HasKey(e => e.CtId)
                    .HasName("PK__Class-Te__DC4E3A7329D191B5");

                entity.Property(e => e.CtId).ValueGeneratedNever();
            });

            modelBuilder.Entity<Subject>(entity =>
            {
                entity.Property(e => e.SubjectId);
            });

            modelBuilder.Entity<Teacher>(entity =>
            {
                entity.HasKey(e => e.Initials)
                    .HasName("PK__Teacher__F6EBAFF7C9157C4A");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}