// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookSmart.Models
{
    [Table("Subject-Teacher")]
    public partial class SubjectTeacher
    {
        [Key]
        [Column("ST_id")]
        public int StId { get; set; }
        [StringLength(4)]
        [Unicode(false)]
        public string Initials { get; set; }
        [Column("Subject_id")]
        public int? SubjectId { get; set; }

        [ForeignKey("Initials")]
        [InverseProperty("SubjectTeachers")]
        public virtual Teacher InitialsNavigation { get; set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("SubjectTeachers")]
        public virtual Subject Subject { get; set; }
    }
}