// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookSmart.Models
{
    [Table("Teacher")]
    public partial class Teacher
    {
        [Key]
        [StringLength(4)]
        [Unicode(false)]
        public string Initials { get; set; }
        [StringLength(40)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(40)]
        [Unicode(false)]
        public string Mail { get; set; }
        

    }
}